### ISSUE TITLE
how to set PDF417EncodingOptions.Dimensions.MaxCols in VBA?

### ISSUE THREAD

**Issue by guyuantian** [micjahn/ZXing.Net#426]
I'm using ZXing.Net in VBA to generate PDF417 barcode.

I want to set the property PDF417EncodingOptions.Dimensions.MaxCols, but it failed.

For example, there are a total of 19 columns here, I want to limit the maximum number of columns to 10.
![image](https://user-images.githubusercontent.com/105156880/172795268-1ddefcd3-332e-4087-a3a9-42a6ad0d583e.png)

Here are my VBA codes:
```
Sub test()

    Dim writer As New BarcodeWriter, myOptions As New PDF417EncodingOptions
    
    writer.Format = BarcodeFormat_PDF_417
    
    myOptions.Margin = 0
    myOptions.Dimensions.MaxCols = 10
        
    Set writer.options = myOptions
    
    Dim s As String, p As String
    s = "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
    p = "D:\Desktop\test.png"
    
    writer.WriteToFile s, p, ImageFileFormat_Png
    
End Sub
```
![image](https://user-images.githubusercontent.com/105156880/172795969-b4318d63-b326-4244-ba7f-4b2049fd2cc8.png)
Error: Can't assign to read-only property

Is there any way to set the MaxCols of PDF417?

I hope these properties can be customized: MaxCols, MaxRows, MinCols, MinRows.

**Comment by micjahn** [comment]
I fear you can't at the moment. The class "Dimensions" uses a constructor with parameters. But I think there is no way to call that constructor inside VBA. Needs to be fixed.

**Comment by guyuantian** [comment]
> I fear you can't at the moment. The class "Dimensions" uses a constructor with parameters. But I think there is no way to call that constructor inside VBA. Needs to be fixed.

Is this a bug that needs to be fixed?

I really hope these properties can be customized...

**Comment by micjahn** [comment]
[zxing.interop_20220610.zip](https://github.com/micjahn/ZXing.Net/files/8876123/zxing.interop_20220610.zip)
Please try this version.

**Comment by guyuantian** [comment]
> [zxing.interop_20220610.zip](https://github.com/micjahn/ZXing.Net/files/8876123/zxing.interop_20220610.zip) Please try this version.
@micjahn 

![snap_screen_20220610140858](https://user-images.githubusercontent.com/105156880/173001543-111320e8-3f9d-429a-b965-59450fde89e4.png)

I copy "zxing.interop.dll" to "c:\windows", execute “register.cmd". But it fails to register this dll file.

**Comment by guyuantian** [comment]
I used an old version of "zxing.dll" in "ZXing.Net.0.16.7.0.zip", and now the dll file is successfully registered.

I run the vba script, it still has error:
![snap_screen_20220610150348](https://user-images.githubusercontent.com/105156880/173009368-0eebcaee-ce08-4b56-9909-e738a04e6839.png)
error 91: Object variable or With block variable not set.

**Comment by micjahn** [comment]
[zxing.interop_20220620.zip](https://github.com/micjahn/ZXing.Net/files/8943466/zxing.interop_20220620.zip)

Sorry for the late answer. Did find enough free time before.
Please try the new version which should fix the error.
It is now built against zxing 0.16.8

**Comment by guyuantian** [comment]
> [zxing.interop_20220620.zip](https://github.com/micjahn/ZXing.Net/files/8943466/zxing.interop_20220620.zip)
> 
> Sorry for the late answer. Did find enough free time before. Please try the new version which should fix the error. It is now built against zxing 0.16.8

I tried this version, still error...

Automation Error?
![image](https://user-images.githubusercontent.com/105156880/174678081-1e3e93a5-5c34-4a52-9b8e-5b39fad31142.png)

**Comment by micjahn** [comment]
I didn't change anything at that line. Perhaps Word/Excel did load the wrong assembly? Not sure.

**Comment by guyuantian** [comment]
> I didn't change anything at that line. Perhaps Word/Excel did load the wrong assembly? Not sure.

This is my installation method, it should be correct, right?
1、Copy the zxing.dll and register.cmd of ZXing.Net.0.16.8.0.zip to the Windows directory (C:\Windows) 
2、Copy the zxing.interop.dll of zxing.interop_20220620.zip to the Windows directory (C:\Windows)
3、Execute the register.cmd
``
@ECHO OFF

reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /i "x86" > NUL && set OS=32BIT || set OS=64BIT

"%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\regasm.exe" /unregister "%~dp0zxing.interop.dll"
"%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\regasm.exe" /codebase "%~dp0zxing.interop.dll" /tlb "%~dp0zxing.interop.tlb"

if %OS%==64BIT "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe" /unregister "%~dp0zxing.interop.dll"
if %OS%==64BIT "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\regasm.exe" /codebase "%~dp0zxing.interop.dll" /tlb "%~dp0zxing.interop.tlb"

pause
``
4、Add vba reference
![image](https://user-images.githubusercontent.com/105156880/174679798-73f8f8f5-727c-48a5-a560-1bc10f1008fd.png)
![image](https://user-images.githubusercontent.com/105156880/174679851-4bb95ff5-d7f8-4996-8b09-236ae33d60c0.png)

**Comment by guyuantian** [comment]
> The installation steps are correct. Does it work if you switch back to version zxing.interop_20220610.zip?

0.16.8+20220610: can't register
![test1](https://user-images.githubusercontent.com/105156880/174929129-395c6608-90c6-4ed1-b5f9-d50d5f24afa0.gif)

0.16.7+20220610: successfully registered, but the code report error
![test2](https://user-images.githubusercontent.com/105156880/174929694-1137d555-cb70-48af-bce6-25533a9be690.gif)

**Comment by micjahn** [comment]
Another try. I put everything you need inside the zip archive. It should work now, hopefully.
[zxing.interop_20220626.zip](https://github.com/micjahn/ZXing.Net/files/8987550/zxing.interop_20220626.zip)

**Comment by guyuantian** [comment]
> Another try. I put everything you need inside the zip archive. It should work now, hopefully. [zxing.interop_20220626.zip](https://github.com/micjahn/ZXing.Net/files/8987550/zxing.interop_20220626.zip)

With this version, the codes no longer report errors.

But setting MaxCols has no effort... Still can't limit the maximum number of columns...

![test111](https://user-images.githubusercontent.com/105156880/175849223-acdcaa8b-ab26-4696-9d2e-098fd0e0d3d1.gif)

**Comment by guyuantian** [comment]
> Sorry, my fault. I forgot something to mention. Because of the way works how it works in the background you have to modify your code a little bit. Please try the following. Perhaps I will find another way in the future for a more intuitive use.
> 
> ```
> Sub test()
> 
>     Dim writer As New BarcodeWriter, myOptions As New PDF417EncodingOptions
>     Dim myDimensions As Dimensions
> 
>     writer.Format = BarcodeFormat_PDF_417
>     
>     myOptions.Margin = 0
>     Set myDimensions = myOptions.Dimensions
>     myDimensions.MaxCols = 10
>     Set myOptions.Dimensions = myDimensions
>         
>     Set writer.options = myOptions
>     
>     Dim s As String, p As String
>     s = "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
>     p = "D:\Desktop\test.png"
>     
>     writer.WriteToFile s, p, ImageFileFormat_Png
>     
> End Sub
> ```

YES! Finally it works with your method!!!
Thank you so much!!! @micjahn  ^_^

**Comment by micjahn** [comment]
[zxing.interop_20220628.zip](https://github.com/micjahn/ZXing.Net/files/9004569/zxing.interop_20220628.zip)

This new version should now work as expected

```
Sub test()

    Dim writer As New BarcodeWriter, myOptions As New PDF417EncodingOptions

    writer.Format = BarcodeFormat_PDF_417
    
    myOptions.Margin = 0
    myOptions.Dimensions.MaxCols = 10
        
    Set writer.options = myOptions
    
    Dim s As String, p As String
    s = "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
    p = "D:\Desktop\test.png"
    
    writer.WriteToFile s, p, ImageFileFormat_Png
    
End Sub
```

**Comment by guyuantian** [comment]
> [zxing.interop_20220628.zip](https://github.com/micjahn/ZXing.Net/files/9004569/zxing.interop_20220628.zip)
> 
> This new version should now work as expected
> 
> ```
> Sub test()
> 
>     Dim writer As New BarcodeWriter, myOptions As New PDF417EncodingOptions
> 
>     writer.Format = BarcodeFormat_PDF_417
>     
>     myOptions.Margin = 0
>     myOptions.Dimensions.MaxCols = 10
>         
>     Set writer.options = myOptions
>     
>     Dim s As String, p As String
>     s = "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
>     p = "D:\Desktop\test.png"
>     
>     writer.WriteToFile s, p, ImageFileFormat_Png
>     
> End Sub
> ```

This version is perfect!!!
